Support Erlang 24 by using mac/3
In Erlang 24, the `hmac/4` function has been removed. `mac/3` replaces
it, but `mac/3` is only available in Erlang >= 22. Support both
depending on what the `:crypto` module exports.

Also fix a `meck`-related compile error by updating to the latest
version:

```
$ mix deps.compile
==> meck (compile)
src/meck_code_gen.erl:182:42: erlang:get_stacktrace/0 is removed; use the new try/catch syntax for retrieving the stack backtrace
Compiling src/meck_code_gen.erl failed:
ERROR: compile failed while processing signaturex/deps/meck: rebar_abort
** (Mix) Could not compile dependency :meck, "elixir/1.12.2/.mix/rebar compile skip_deps=true deps_dir="signaturex/_build/test/lib"" command failed. You can recompile this dependency with "mix deps.compile meck", update it with "mix deps.update meck" or clean it with "mix deps.clean meck"
```

Also fix a compile warning about the application setup and `crypto` by
adding `extra_applications` to the `mix.exs` file:

```
warning: :crypto.hash/2 defined in application :crypto is used by the current application but the current application does not depend on :crypto. To fix this, you must do one of:

  1. If :crypto is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :crypto is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :crypto, you may optionally skip this warning by adding [xref: [exclude: [:crypto]]] to your "def project" in mix.exs

  lib/signaturex/crypto_helper.ex:37: Signaturex.CryptoHelper.md5/1
```

Fixes #8.